INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('1', 'Afghanistan', 'Afghani', 'AFN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('2', 'Albania', 'Lek', 'ALL', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('3', 'Argentina', 'Peso', 'ARS', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('4', 'Aruba', 'Guilder', 'AWG', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('5', 'Australia', 'Dollar', 'AUD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('6', 'Azerbaijan', 'Manat', 'AZN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('7', 'Bahamas', 'Dollar', 'BSD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('8', 'Barbados', 'Dollar', 'BBD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('9', 'Belarus', 'Ruble', 'BYN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('10', 'Belize', 'Dollar', 'BZD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('11', 'Bermuda', 'Dollar', 'BMD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('12', 'Bolivia', 'Bol�viano', 'BOB', 'fa fa-dollarb');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('13', 'Bosnia and Herzegovina', ' Convertible Marka', 'bam', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('14', 'Botswana', 'Pula', 'BWP', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('15', 'Bulgaria', 'Lev', 'BGN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('16', 'Brazil `', 'Real', 'BRL', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('17', 'Brunei', 'Brunei Dollar', 'BND', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('18', 'Cambodia', 'Riel', 'KHR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('19', 'Canada', 'Dollar', 'CAD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('20', 'Cayman Islands', 'Dollar', 'KYD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('21', 'Chile', 'Peso', 'CLP', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('22', 'China', 'Yuan Renminbi', 'CNY', 'fa fa-yen');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('23', 'Colombia', 'Peso', 'COP', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('24', 'Costa Rica', 'Colon', 'CRC', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('25', 'Croatia', 'Kuna', 'HRK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('26', 'Cuba', 'Peso', 'CUP', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('27', 'Czech Republic', 'Koruna', 'CZK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('28', 'Denmark', 'Krone', 'DKK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('29', 'Dominican Republic', 'Peso', 'DOP', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('30', 'East Caribbean', 'Dollar', 'XCD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('31', 'Egypt', 'Pound', 'EGP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('32', 'El Salvador', 'Colon', 'SVC', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('33', 'Euro Member Countries', 'EUR', 'EUR', 'fa fa-eur');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('34', 'Falkland Islands (Malvinas)', 'Pound', 'FKP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('35', 'Fiji', 'Dollar', 'FJD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('36', 'Ghana', 'Cedi', 'GHS', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('37', 'Gibraltar', 'Pound', 'GIP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('38', 'Guatemala', 'Quetzal', 'GTQ', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('39', 'Guernsey', 'Pound', 'GGP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('40', 'Guyana', 'Dollar', 'GYD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('41', 'Honduras', 'Lempira', 'HNL', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('42', 'Hong Kong', 'Dollar', 'HKD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('43', 'Hungary', 'Forint', 'HUF', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('44', 'Iceland', 'Krona', 'ISK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`, `country_calling_code`) VALUES ('45', 'India', 'Rupee', 'INR', 'fa fa-rupee', '91');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('46', 'Indonesia', 'Rupiah', 'IDR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('47', 'Iran', 'Rial', 'IRR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('48', 'Isle of Man', 'Pound', 'IMP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('49', 'Israel', 'Shekel', 'ILS', 'fa fa-sheqel');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('50', 'Jamaica', 'Dollar', 'JMD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('51', 'Japan', 'Yen', 'JPY', 'fa fa-yen');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('52', 'Jersey', 'Pound', 'JEP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('53', 'Kazakhstan', 'Tenge', 'KZT', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('54', 'Korea (North)', 'Won', 'KPW', 'fa fa-krw');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('55', 'Korea (South)', 'Won', 'KRW', 'fa fa-krw');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('56', 'Kyrgyzstan', 'Som', 'KGS', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('57', 'Laos', 'Kip', 'LAK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('58', 'Lebanon', 'Pound', 'LBP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('59', 'Liberia', 'Dollar', 'LRD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('60', 'Macedonia', 'Denar', 'MKD', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('61', 'Malaysia', 'Ringgit', 'MYR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('62', 'Mauritius', 'Rupee', 'MUR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('63', 'Mexico', 'Peso', 'MXN', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('64', 'Mongolia', 'Tughrik', 'MNT', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('65', 'Mozambique', 'Metical', 'MZN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('66', 'Namibia', 'Dollar', 'NAD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('67', 'Nepal', 'Rupee', 'NPR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('68', 'Netherlands', 'Antilles Guilder', 'ANG', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('69', 'New Zealand', 'Dollar', 'NZD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('70', 'Nicaragua', 'Cordoba', 'NIO', 'Cfa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('71', 'Nigeria', 'Naira', 'NGN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('72', 'Norway', 'Krone', 'NOK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('73', 'Oman', 'Rial', 'OMR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('74', 'Pakistan', 'Rupee', 'PKR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('75', 'Panama', 'Balboa', 'PAB', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('76', 'Paraguay', 'Guarani', 'PYG', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('77', 'Peru', 'Sol', 'PEN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('78', 'Philippines', 'Peso', 'PHP', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('79', 'Poland', 'Zloty', 'PLN', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('80', 'Qatar', 'Riyal', 'QAR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('81', 'Romania', 'Leu', 'RON', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('82', 'Russia', 'Ruble', 'RUB', 'fa fa-ruble');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('83', 'Saint Helena', 'Pound', 'SHP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('84', 'Saudi Arabia', 'Riyal', 'SAR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('85', 'Serbia', 'Dinar', 'RSD', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('86', 'Seychelles `', 'Rupee', 'SCR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('87', 'Singapore', 'Dollar', 'SGD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('88', 'Solomon Islands', 'Dollar', 'SBD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('89', 'Somalia', 'Shilling', 'SOS', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('90', 'South Africa', 'Rand', 'ZAR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('91', 'Sri Lanka', 'Rupee', 'LKR', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('92', 'Sweden', 'Krona', 'SEK', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('93', 'Switzerland', 'Franc', 'CHF', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('94', 'Suriname', 'Dollar', 'SRD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('95', 'Syria', 'Pound', 'SYP', 'fa fa-gbp');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('96', 'Taiwan', 'New Dollar', 'TWD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('97', 'Thailand', 'Baht', 'THB', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('98', 'Trinidad and Tobago', 'Dollar', 'TTD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('99', 'Turkey', 'Lira', 'TRY', 'fa fa-try');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('100', 'Tuvalu', 'Dollar', 'TVD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('101', 'Ukraine', 'Hryvnia', 'UAH', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`, `country_calling_code`) VALUES ('102', 'United Kingdom (UK)', 'Pound', 'GBP', 'fa fa-gbp', '44');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`, `country_calling_code` ) VALUES ('103', 'United States (USA)', 'Dollar', 'USD', 'fa fa-dollar', '1');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('104', 'Uruguay', 'Peso', 'UYU', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('105', 'Uzbekistan', 'Som', 'UZS', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('106', 'Venezuela', 'Bol�var', 'VEF', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('107', 'Vietnam', 'Dong', 'VND', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('108', 'Yemen', 'Rial', 'YER', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('109', 'Zimbabwe', 'Dollar', 'ZWD', 'fa fa-dollar');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('110', 'Bangladesh', 'Taka', 'BDT', 'fa fa-money');
INSERT INTO `alpide-lookup`.`bo_country` (`country_id`, `country_name`, `currency_name`, `currency_code`, `currency_icon`) VALUES ('111', 'Germany', 'Euro', 'EUR', 'fa fa-eur');





INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'Ak', 'Alaska', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'TX', 'Texas', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'AL', 'Alabama', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'AZ', 'Arizona', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'AR', 'Arkansas', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'CA', 'California', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'CO', 'Colorado', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'CT', 'Connecticut', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'DE', 'Delaware', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'FL', 'Florida', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'GA', 'Georgia', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'HI', 'Hawaii', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'ID', 'Idaho', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'IL', 'Illinois', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'IN', 'Indiana', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'IA', 'Iowa', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'KS', 'Kansas', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'LA', 'Louisiana', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'ME', 'Maine', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MD', 'Maryland', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MA', 'Massachusetts', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MI', 'Michigan', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MS', 'Minnesota', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MS', 'Mississippi', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MO', 'Missouri', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'MT', 'Montana', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NE', 'Nebraska', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NV', 'Nevada', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NH', 'New Hampshire', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NJ', 'New Jersey', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NM', 'New Mexico', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NY', 'New York', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'NC', 'North Carolina', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'ND', 'North Dakota', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'OH', 'Ohio', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'OK', 'Oklahoma', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'OR', 'Oregon', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'PA', 'Pennsylvania', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'RI', 'Rhode Island', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'SC', 'South Carolina', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'SD', 'South Dakota', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'TN', 'Tennessee', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'UT', 'Utah', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'VT', 'Vermont', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'VA', 'Virginia', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'WV', 'West Virginia', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'WA', 'Washington', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'WI', 'Wisconsin', '103');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_short_name`, `state_name`, `country_id`) VALUES ('0', 'WY', 'Wyoming', '103');

ALTER TABLE `alpide-lookup`.`states` ADD COLUMN ut INT;


INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Andhra Pradesh', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Arunachal Pradesh', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Assam', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Bihar', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Chhattisgarh', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Goa', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Gujarat', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Haryana', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Himachal Pradesh', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Jammu & Kashmi', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Jharkhand', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Karnataka', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Kerala', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Madhya Pradesh', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Maharashtra', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Manipur', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Meghalaya', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Mizoram', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Nagaland', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Orissa', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Punjab', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Rajasthan', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Sikkim', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Tamil Nadu', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Telangana', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Tripura', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Uttar Pradesh', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Uttarakhand', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'West Bengal', '1', 'India', '0');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Andaman & Nicobar Islands', '1', 'India', '1');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Dadra and Nagar Haveli', '1', 'India', '1');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Daman and Diu', '1', 'India', '1');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Lakshadweep', '1', 'India', '1');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Puducherry', '1', 'India', '1');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Delhi', '1', 'India', '1');
INSERT INTO `alpide-lookup`.`states` (`state_id`, `state_name`, `country_id`, `country_name`, `ut`) VALUES ('0', 'Chandigarh', '1', 'India', '1');