CREATE TABLE `alpide-lookup`.`pick_exception` (
  `exception_id` bigint NOT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `exception_name` varchar(255) DEFAULT NULL,
  `rid` bigint DEFAULT NULL,
  `version` int NOT NULL,
  PRIMARY KEY (`exception_id`)
);

CREATE TABLE `alpide-lookup`.`lk_pick_instruction` (
  `pick_instruction_id` bigint NOT NULL AUTO_INCREMENT,
  `created_by_user_id` bigint DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `pick_instruction` varchar(255) DEFAULT NULL,
  `rid` bigint DEFAULT NULL,
  `version` int NOT NULL,
  PRIMARY KEY (`pick_instruction_id`)
);

CREATE TABLE `alpide-lookup`.`lk_handling_instruction` (
  `handling_instruction_id` bigint NOT NULL AUTO_INCREMENT,
  `created_by_user_id` bigint DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `handling_instruction` varchar(255) DEFAULT NULL,
  `rid` bigint DEFAULT NULL,
  `version` int NOT NULL,
  PRIMARY KEY (`handling_instruction_id`)
);

-- This table is used to store packing slip master records
CREATE TABLE `alpide-sales`.`wms_packing_slip_master` (
  `packing_slip_master_id` bigint NOT NULL AUTO_INCREMENT,
  `customer_id` bigint DEFAULT NULL,
  `packed_by_emp_id` bigint DEFAULT NULL,
  `packing_slip_number` varchar(30) NOT NULL,
  `packing_status` varchar(30) DEFAULT NULL,
  `rid` bigint NOT NULL,
  `remarks` text,
  `sales_order_master_id` bigint DEFAULT NULL,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `date_deleted` datetime(6) DEFAULT NULL,
  `date_inactivated` datetime(6) DEFAULT NULL,
  `date_updated` datetime(6) DEFAULT NULL,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  PRIMARY KEY (`packing_slip_master_id`),
  UNIQUE KEY `UK_8cb9u73sfaaeachd3wgcmuj1f` (`packing_slip_number`)
);

-- This table is used to store details of packing slips
CREATE TABLE `alpide-sales`.`wms_packing_slip_details` (
  `packing_slip_detail_id` bigint NOT NULL AUTO_INCREMENT,
  `batch_id` bigint DEFAULT NULL,
  `bin_id` bigint DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `is_split_pick` bit(1) DEFAULT NULL,
  `item_id` bigint DEFAULT NULL,
  `line_status` varchar(255) DEFAULT NULL,
  `package_unit_id` bigint DEFAULT NULL,
  `picking_strategy` varchar(255) DEFAULT NULL,
  `qty_ordered` double DEFAULT NULL,
  `qty_to_pack` double DEFAULT NULL,
  `sales_order_detail_id` bigint DEFAULT NULL,
  `packing_slip_master_id` bigint NOT NULL,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `date_deleted` datetime(6) DEFAULT NULL,
  `date_inactivated` datetime(6) DEFAULT NULL,
  `date_updated` datetime(6) DEFAULT NULL,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  PRIMARY KEY (`packing_slip_detail_id`),
  KEY `FKgvqqyde3sf57295qqpeic5sog` (`packing_slip_master_id`),
  CONSTRAINT `FKgvqqyde3sf57295qqpeic5sog` FOREIGN KEY (`packing_slip_master_id`) REFERENCES `wms_packing_slip_master` (`packing_slip_master_id`)
);


CREATE TABLE `alpide-sales`.`wms_pick_task_master` (
  `pick_task_master_id` int NOT NULL AUTO_INCREMENT,
  `picker_emp_id` bigint DEFAULT NULL,
  `sales_order_id` int DEFAULT NULL,
  `rid` bigint NOT NULL,
  `pick_priority` varchar(30) DEFAULT NULL,
  `pick_status` varchar(30) DEFAULT NULL,
  `remarks` text,
  `customer_id` bigint DEFAULT NULL,
  `pick_task_number` varchar(30) NOT NULL,
  `sales_order_master_id` bigint DEFAULT NULL,
  `pick_by_emp_id` bigint DEFAULT NULL,
  `customer_name` varchar(55) DEFAULT NULL,
  `so_number` varchar(55) DEFAULT NULL,
  `due_date` timestamp NULL DEFAULT NULL,
  `status` varchar(30) DEFAULT NULL,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `date_deleted` timestamp NULL DEFAULT NULL,
  `date_inactivated` timestamp NULL DEFAULT NULL,
  `date_updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  PRIMARY KEY (`pick_task_master_id`),
  UNIQUE KEY `UK_a77ahnkqelndwa94t3siymrwx` (`pick_task_number`)
);

CREATE TABLE `alpide-sales`.`wms_pick_task_details` (
  `is_split_pick` bit(1) DEFAULT NULL,
  `pick_task_master_id` int DEFAULT NULL,
  `qty_ordered` double DEFAULT NULL,
  `qty_to_pick` double DEFAULT NULL,
  `bin_id` bigint DEFAULT NULL,
  `item_id` bigint DEFAULT NULL,
  `pick_task_detail_id` bigint NOT NULL AUTO_INCREMENT,
  `sales_order_detail_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `line_status` varchar(255) DEFAULT NULL,
  `picking_strategy` varchar(255) DEFAULT NULL,
  `handling_instructions` varchar(255) DEFAULT NULL,
  `special_instructions` varchar(255) DEFAULT NULL,
  `attribute_id1` bigint DEFAULT NULL,
  `attribute_id2` bigint DEFAULT NULL,
  `attribute_id3` bigint DEFAULT NULL,
  `attribute_name1` varchar(255) DEFAULT NULL,
  `attribute_name2` varchar(255) DEFAULT NULL,
  `attribute_name3` varchar(255) DEFAULT NULL,
  `attribute_value1` varchar(255) DEFAULT NULL,
  `attribute_value2` varchar(255) DEFAULT NULL,
  `attribute_value3` varchar(255) DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `item_variant_id` bigint DEFAULT NULL,
  `item_variant_name` varchar(255) DEFAULT NULL,
  `item_variant_stock_id` bigint DEFAULT NULL,
  `rate` double DEFAULT NULL,
  `relationship_id` bigint DEFAULT NULL,
  `sales_order_master_id` bigint DEFAULT NULL,
  `sku` varchar(255) DEFAULT NULL,
  `stock_deduction_type` varchar(255) DEFAULT NULL,
  `uom_name` varchar(255) DEFAULT NULL,
  `warehouse` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `storage_bin_id` bigint DEFAULT NULL,
  `storage_bin_name` varchar(50) DEFAULT NULL,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `date_deleted` datetime(6) DEFAULT NULL,
  `date_inactivated` datetime(6) DEFAULT NULL,
  `date_updated` datetime(6) DEFAULT NULL,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  PRIMARY KEY (`pick_task_detail_id`),
  KEY `FKmuquwlr5kss0ebuw1nxn82dx4` (`pick_task_master_id`),
  CONSTRAINT `FKmuquwlr5kss0ebuw1nxn82dx4` FOREIGN KEY (`pick_task_master_id`) REFERENCES `wms_pick_task_master` (`pick_task_master_id`)
);

CREATE TABLE `alpide-sales`.`wms_pick_ticket_closure_master` (
  `pick_ticket_closure_master_id` bigint NOT NULL AUTO_INCREMENT,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `date_deleted` datetime(6) DEFAULT NULL,
  `date_inactivated` datetime(6) DEFAULT NULL,
  `date_updated` datetime(6) DEFAULT NULL,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  `date_closed` datetime(6) NOT NULL,
  `device_id` varchar(50) DEFAULT NULL,
  `document_number` varchar(30) NOT NULL,
  `exception_resolved` bit(1) NOT NULL,
  `order_number` varchar(30) DEFAULT NULL,
  `pick_task_master_id` bigint NOT NULL,
  `picker_id` bigint DEFAULT NULL,
  `picker_name` varchar(100) DEFAULT NULL,
  `relationship_id` bigint DEFAULT NULL,
  `remarks` text,
  `routing_method` varchar(50) DEFAULT NULL,
  `warehouse_location` varchar(100) DEFAULT NULL,
  `wave_id` varchar(30) DEFAULT NULL,
  `work_shift` varchar(50) DEFAULT NULL,
  `zone_area` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`pick_ticket_closure_master_id`),
  UNIQUE KEY `UK_86l6o20yxlaypcoitfp4siui3` (`document_number`)
);

CREATE TABLE `alpide-sales`.`wms_pick_ticket_closure_details` (
  `pick_ticket_closure_detail_id` bigint NOT NULL AUTO_INCREMENT,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `date_deleted` datetime(6) DEFAULT NULL,
  `date_inactivated` datetime(6) DEFAULT NULL,
  `date_updated` datetime(6) DEFAULT NULL,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  `batch_number` varchar(50) DEFAULT NULL,
  `bin_location` varchar(50) DEFAULT NULL,
  `expiration_date` datetime(6) DEFAULT NULL,
  `item_variant_id` bigint NOT NULL,
  `item_description` text,
  `item_id` bigint NOT NULL,
  `quantity_picked` double DEFAULT NULL,
  `quantity_requested` double DEFAULT NULL,
  `reason` varchar(2000) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `uom` varchar(20) DEFAULT NULL,
  `volume` double DEFAULT NULL,
  `weight` double DEFAULT NULL,
  `pick_ticket_closure_master_id` bigint NOT NULL,
  PRIMARY KEY (`pick_ticket_closure_detail_id`),
  KEY `FKgg5ph72ecg5b9i9o6ajd54x08` (`pick_ticket_closure_master_id`),
  CONSTRAINT `FKgg5ph72ecg5b9i9o6ajd54x08` FOREIGN KEY (`pick_ticket_closure_master_id`) REFERENCES `wms_pick_ticket_closure_master` (`pick_ticket_closure_master_id`)
);

-- This table is used to store exceptions related to pick tickets
CREATE TABLE `alpide-sales`.`wms_pick_ticket_exception` (
  `pick_ticket_exception_id` bigint NOT NULL AUTO_INCREMENT,
  `created_by_emp_id` int DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `date_deleted` datetime(6) DEFAULT NULL,
  `date_inactivated` datetime(6) DEFAULT NULL,
  `date_updated` datetime(6) DEFAULT NULL,
  `deleted_by_emp_id` int DEFAULT NULL,
  `inactivated_by_emp_id` int DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `updated_by_emp_id` int DEFAULT NULL,
  `comments` varchar(2000) DEFAULT NULL,
  `exception_number` varchar(50) DEFAULT NULL,
  `item_variant_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `pick_task_master_id` bigint NOT NULL,
  `pick_task_number` varchar(50) NOT NULL,
  `pick_ticket_closure_number` varchar(50) DEFAULT NULL,
  `quantity` double DEFAULT NULL,
  `quantity_picked` double DEFAULT NULL,
  `rid` bigint DEFAULT NULL,
  `so_master_id` bigint NOT NULL,
  `so_number` varchar(50) NOT NULL,
  `status` varchar(50) DEFAULT NULL,
  `uom` varchar(20) DEFAULT NULL,
  `pick_ticket_closure_details_id` bigint DEFAULT NULL,
  PRIMARY KEY (`pick_ticket_exception_id`),
  UNIQUE KEY `UK_lb0d89yxkhpaxhsq5o7bwikx7` (`exception_number`),
  KEY `FK2ovxc04t359l1oudnxnjum7dl` (`pick_ticket_closure_details_id`),
  CONSTRAINT `FK2ovxc04t359l1oudnxnjum7dl` FOREIGN KEY (`pick_ticket_closure_details_id`) REFERENCES `wms_pick_ticket_closure_details` (`pick_ticket_closure_detail_id`)
);